steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '--build-arg', 'FLASK_ENV=production',
      './backend'
    ]

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--update-env-vars',
      'FLASK_ENV=production',
      '--update-env-vars',
      'DATABASE_NAME=universal_matching_db',
      '--update-env-vars',
      'AUTH_PROVIDER=firebase',
      '--update-env-vars',
      'AUTH_PROJECT_ID=universalmatchingv2',
      '--update-env-vars',
      'STORAGE_PROVIDER=gcs',
      '--update-env-vars',
      'STORAGE_PROJECT_ID=universalmatchingv2',
      '--update-env-vars',
      'STORAGE_BUCKET_NAME=universalmatchingv2',
      '--update-env-vars',
      'DATABASE_CONNECTION_STRING=mongodb+srv://richardjiangfrm:LM3cw8L9PXggrOCY@cluster0.x69rk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0',
      '--update-env-vars',
      'JWT_SECRET_KEY=f89e7b8b7b3d42f3a5e8d7c3f89e7b8b7b3d42f3a5e8d7c3f89e7b8b7b3d42f3',
      '--update-env-vars',
      'AUTH_CREDENTIALS_PATH=/secrets/firebase-credentials.json',
      '--update-env-vars',
      'STORAGE_CREDENTIALS_PATH=/secrets/firebase-credentials.json',
      '--update-env-vars',
      'CORS_ORIGINS=["https://universalmatchingv2.web.app","https://universalmatchingv2.firebaseapp.com","https://universalmatchingv2-181579031870.asia-southeast1.run.app","http://localhost:5173"]'
    ]

substitutions:
  _SERVICE_NAME: universalmatchingv2
  _REGION: asia-southeast1

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA' 