steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/universalmatchingv2', './backend']
    env:
      - 'FLASK_ENV=production'
      - 'PORT=8080'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/universalmatchingv2']

  # Get existing environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        EXISTING_ENV=$(gcloud run services describe universalmatchingv2 --region=asia-southeast1 --format='get(spec.template.spec.containers[0].env)' --platform=managed)
        gcloud run deploy universalmatchingv2 \
          --image gcr.io/$PROJECT_ID/universalmatchingv2 \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated \
          --update-env-vars "FLASK_ENV=production" \
          --set-env-vars "$EXISTING_ENV"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/universalmatchingv2' 